### PR TITLE
Ruff linter/autofixer

### PR DESCRIPTION
**Pull request by mjurbanski-reef**
From 100 problems 14 were automatically fixable by the tool.
Rest of them are mostly due ruff inability to work with star imports. I.e. if we were to ignore F403 and F405 in every file we would be just left with:
```
b2sdk/__init__.py:24:1: E402 Module level import not at top of file
doc/source/conf.py:34:1: E402 Module level import not at top of file
noxfile.py:105:21: E741 Ambiguous variable name: `l`
test/unit/sync/test_sync.py:726:13: E722 Do not use bare `except`
test/unit/sync/test_sync.py:771:13: E722 Do not use bare `except`
Found 5 errors.
```

below is full output of `ruff check .`  with the pyproject.toml as provided in this PR. The PR itself already contains automatc fixes applied.
```
b2sdk/__init__.py:24:1: E402 Module level import not at top of file
b2sdk/sync/exception.py:12:30: F401 [*] `..scan.exception.BaseDirectoryError` imported but unused
b2sdk/v0/exception.py:15:19: F405 `DestFileNewer` may be undefined, or defined from star imports: `b2sdk.v1.exception`
b2sdk/v1/__init__.py:34:12: F405 `B2RawHTTPApi` may be undefined, or defined from star imports: `b2sdk.v2`
b2sdk/v1/exception.py:12:19: F405 `DestFileNewer` may be undefined, or defined from star imports: `b2sdk.v2.exception`
b2sdk/v1/exception.py:16:20: F405 `B2Error` may be undefined, or defined from star imports: `b2sdk.v2.exception`
b2sdk/v1/sync/__init__.py:11:1: F403 `from .encryption_provider import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:12:1: F403 `from .file import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:13:1: F403 `from .folder import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:14:1: F403 `from .folder_parser import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:15:1: F403 `from .report import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:16:1: F403 `from .scan_policies import *` used; unable to detect undefined names
b2sdk/v1/sync/__init__.py:17:1: F403 `from .sync import *` used; unable to detect undefined names
b2sdk/v2/exception.py:13:22: F405 `BucketIdNotFound` may be undefined, or defined from star imports: `b2sdk._v3.exception`
b2sdk/v2/exception.py:14:22: F405 `UnsupportedFilename` may be undefined, or defined from star imports: `b2sdk._v3.exception`
b2sdk/v2/exception.py:18:44: F405 `BadRequest` may be undefined, or defined from star imports: `b2sdk._v3.exception`
b2sdk/v2/exception.py:25:22: F405 `BadRequest` may be undefined, or defined from star imports: `b2sdk._v3.exception`
doc/source/conf.py:34:1: E402 Module level import not at top of file
noxfile.py:105:21: E741 Ambiguous variable name: `l`
setup.py:21:23: F401 [*] `importlib.import_module` imported but unused
test/integration/bucket_cleaner.py:13:1: F403 `from b2sdk.v2 import *` used; unable to detect undefined names
test/integration/bucket_cleaner.py:33:45: F405 `Bucket` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:41:27: F405 `current_time_millis` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:57:69: F405 `RetentionMode` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:61:33: F405 `NO_RETENTION_FILE_SETTING` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:63:71: F405 `RetentionMode` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:64:80: F405 `current_time_millis` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:71:71: F405 `RetentionMode` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/bucket_cleaner.py:81:81: F405 `LegalHold` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/helpers.py:11:20: F401 [*] `typing.Optional` imported but unused
test/integration/helpers.py:16:8: F401 [*] `pytest` imported but unused
test/integration/helpers.py:18:1: F403 `from b2sdk.v2 import *` used; unable to detect undefined names
test/integration/helpers.py:30:40: F405 `DEFAULT_HTTP_API_CONFIG` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/helpers.py:31:12: F405 `InMemoryAccountInfo` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/helpers.py:32:14: F405 `B2Api` may be undefined, or defined from star imports: `b2sdk.v2`
test/integration/test_download.py:18:1: F403 `from b2sdk.v2 import *` used; unable to detect undefined names
test/integration/test_download.py:21:1: F403 `from .fixtures import *` used; unable to detect undefined names
test/integration/test_download.py:37:21: F405 `ParallelDownloader` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:48:22: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:59:24: F405 `LARGE_FILE_SHA1` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:60:34: F405 `LARGE_FILE_SHA1` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:63:69: F405 `DownloadVersion` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:65:14: F405 `TempDir` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:80:27: F405 `hex_sha1_of_file` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:81:35: F405 `hex_sha1_of_file` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:98:14: F405 `TempDir` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/integration/test_download.py:120:36: F405 `B2HttpApiConfig` may be undefined, or defined from star imports: `.fixtures`, `b2sdk.v2`
test/unit/account_info/test_account_info.py:31:1: F403 `from .fixtures import *` used; unable to detect undefined names
test/unit/account_info/test_account_info.py:43:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:48:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:63:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:84:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:99:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:118:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:159:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:161:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:163:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:165:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:167:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:169:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:171:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:176:18: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:179:18: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:181:18: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:259:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:289:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:334:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:354:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:362:9: F841 [*] Local variable `s` is assigned to but never used
test/unit/account_info/test_account_info.py:373:14: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_account_info.py:376:6: F405 `pytest` may be undefined, or defined from star imports: `.fixtures`
test/unit/account_info/test_sqlite_account_info.py:12:8: F401 [*] `unittest.mock` imported but unused
test/unit/account_info/test_sqlite_account_info.py:24:1: F403 `from .fixtures import *` used; unable to detect undefined names
test/unit/api/test_api.py:22:25: F401 [*] `apiver_deps.DummyCache` imported but unused
test/unit/bucket/test_bucket.py:28:5: F401 [*] `apiver_deps_exception.BadRequest` imported but unused
test/unit/bucket/test_bucket.py:1583:27: F841 [*] Local variable `d` is assigned to but never used
test/unit/fixtures/__init__.py:11:1: F403 `from .b2http import *` used; unable to detect undefined names
test/unit/fixtures/__init__.py:12:1: F403 `from .cache import *` used; unable to detect undefined names
test/unit/fixtures/__init__.py:13:1: F403 `from .raw_api import *` used; unable to detect undefined names
test/unit/fixtures/__init__.py:14:1: F403 `from .session import *` used; unable to detect undefined names
test/unit/sync/test_sync.py:10:8: F401 [*] `io` imported but unused
test/unit/sync/test_sync.py:21:1: F403 `from ..fixtures.folder import *` used; unable to detect undefined names
test/unit/sync/test_sync.py:22:1: F403 `from .fixtures import *` used; unable to detect undefined names
test/unit/sync/test_sync.py:727:13: E722 Do not use bare `except`
test/unit/sync/test_sync.py:772:13: E722 Do not use bare `except`
test/unit/sync/test_sync.py:895:25: F405 `UploadMode` may be undefined, or defined from star imports: `..fixtures.folder`, `.fixtures`
test/unit/test_included_modules.py:12:8: F401 [*] `pytest` imported but unused
test/unit/test_session.py:18:6: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/test_session.py:22:6: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/test_session.py:25:13: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/test_session.py:39:23: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/test_session.py:41:13: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/test_session.py:54:23: F405 `pytest` may be undefined, or defined from star imports: `.account_info.fixtures`, `.fixtures`
test/unit/v0/deps.py:16:1: F403 `from apiver_deps import *` used; unable to detect undefined names
test/unit/v0/deps_exception.py:16:1: F403 `from apiver_deps_exception import *` used; unable to detect undefined names
test/unit/v1/deps.py:16:1: F403 `from apiver_deps import *` used; unable to detect undefined names
test/unit/v1/deps_exception.py:16:1: F403 `from apiver_deps_exception import *` used; unable to detect undefined names
test/unit/v1/test_copy_manager.py:13:29: F401 [*] `.deps_exception.InvalidAuthToken` imported but unused
test/unit/v1/test_copy_manager.py:13:47: F401 [*] `.deps_exception.Unauthorized` imported but unused
test/unit/v1/test_copy_manager.py:15:90: F401 [*] `.deps.SSE_NONE` imported but unused
Found 100 errors.
[*] 14 potentially fixable with the --fix option.
```

### CODE REVIEW

**Comment by ppolewicz** [comment]
This is all good, but I think we should add it to nox and CI too (not to fail anything for now, but to report issues)

**Comment by mjurbanski-reef** [comment]
fixed remaining errors and added to nox & CI - and the results are not ignored - my experience is that if output doesn't return an error then devs will ignore it as well

**Comment by ppolewicz** [comment]
Is there benefit of keeping both ruff and pyflakes?

Does ruff validate doctests too?

**Comment by mjurbanski-reef** [comment]
IMO there is little benefit since ruff aims to be superset of it, but AFAIK it does not validate code in docstrings.
IMO we can just run pytest over these tests and that should be good as any validation of small snipetts of code. (IDK if we test them already or not)

**Pull request merged**
