### PR TITLE
Disable decompression

### PR DESCRIPTION
**Pull request by mpnowacki-reef**

### CODE REVIEW

**Comment by mszumocki-reef** [comment]
No test for decode_content=False?

**Review by mszumocki-reef — APPROVED** [review]

**Comment by mpnowacki-reef** [comment]
> No test for decode_content=False?

It’s the default, so it’s tested (I’m talking about integration tests). Do you think it should be called explicitly?

**Comment by mszumocki-reef** [comment]
Is it tested with a file sent with b2-content-encoding set?

**Comment by mpnowacki-reef** [comment]
Yes, a single file is uploaded and downloaded with two APIs - one with decompression disabled and one with decompression enbaled

**Pull request merged**
