### PR TITLE
Add get_bucket_name_or_none_from_bucket_id to AccountInfo and Cache

### PR DESCRIPTION
**Pull request by mpnowacki-reef**
related to https://github.com/Backblaze/b2-sdk-python/issues/189

### CODE REVIEW

**Review by mszumocki-reef — APPROVED** [review]
Docstrings are a bit inconsistent - some of implementations have them, some don't.
Also, for @abstractmethods, using docsstring or 'pass' might be nicer then 'return None'

**Comment by mpnowacki-reef** [comment]
> Also, for @abstractmethods, using docsstring or 'pass' might be nicer then 'return None'
I agree

**Comment by mpnowacki-reef** [comment]
> Docstrings are a bit inconsistent - some of implementations have them, some don't.

Actually, I tried to keep it consistent with present code: only abstract methods have them (implementations don't, unless it's an inheriting class in apiver - that's different) and not all classes have them - AbstractCache doesn't.

**Comment by mpnowacki-reef** [comment]
replaced by https://github.com/Backblaze/b2-sdk-python/pull/224

**Pull request closed without merging**
