### PR TITLE
Change default fetch count for bucker ls

### PR DESCRIPTION
**Pull request by mlech-reef**

### CODE REVIEW

**Comment by ppolewicz** [comment]
This should fix https://github.com/Backblaze/B2_Command_Line_Tool/issues/659

We've done some testing and it seems the default to fetch 100 does not generally seem to be the best value for b2sdk/b2cli.

**Comment by ppolewicz** [comment]
looks good, please retarget to master and ask Brian to review

**Comment by ppolewicz** [comment]
🤔 add a test maybe?

**Comment by mlech-reef** [comment]
>  add a test maybe?

I don't think we need to test the default values of API parameters in unit tests.

**Comment by ppolewicz** [comment]
ok go ahead and retarget

**Pull request closed without merging**
